name: Python 3.9 compatibility

on:
  push:
  pull_request:

jobs:
  vermin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install vermin
      - run: vermin --target=3.9 --feature union-types --eval-annotations --violations --no-tips handler.py
